# ⚡🌌 AUREON POWER STATION - DIGITAL OCEAN APP PLATFORM
# PRIMARY INTERFACE: Aureon Pro Dashboard (Port 8080)
# All systems are started by supervisord in one service container.

name: aureon-trading
region: lon

services:
  - name: aureon-power-station
    dockerfile_path: Dockerfile
    source_dir: .
    github:
      branch: main
      deploy_on_push: true
      repo: RA-CONSULTING/aureon-trading

    # Ensure App Platform executes the same multi-system startup as local production
    run_command: /app/deploy/validate_startup.sh && /usr/bin/supervisord -n -c /app/deploy/supervisord.conf

    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-d-8vcpu-32gb

    autoscaling:
      min_instance_count: 1
      max_instance_count: 2
      metrics:
        cpu:
          percent: 80
        memory:
          percent: 85

    # Dashboard starts web server first, so health checks can begin earlier.
    health_check:
      http_path: /health
      initial_delay_seconds: 180
      period_seconds: 30
      timeout_seconds: 20
      success_threshold: 1
      failure_threshold: 6

    envs:
      # Runtime/platform basics
      - key: PYTHONUNBUFFERED
        scope: RUN_AND_BUILD_TIME
        value: "1"
      - key: PYTHONIOENCODING
        scope: RUN_AND_BUILD_TIME
        value: "utf-8"
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: MODE
        scope: RUN_TIME
        value: "parallel"

      # Shared state and process controls
      - key: AUREON_STATE_DIR
        scope: RUN_TIME
        value: /app/state
      - key: KRAKEN_NONCE_PATH
        scope: RUN_TIME
        value: /app/state/kraken_nonce.json
      - key: KRAKEN_PRIVATE_LOCK_PATH
        scope: RUN_TIME
        value: /app/state/kraken_private.lock
      - key: AUREON_ENABLE_AUTONOMOUS_CONTROL
        scope: RUN_TIME
        value: "1"
      - key: AUREON_SKIP_KRAKEN_SEED
        scope: RUN_TIME
        value: "1"
      - key: AUREON_REQUIRE_ALL_EXCHANGES
        scope: RUN_TIME
        value: "true"

      # Trading mode
      - key: LIVE
        scope: RUN_TIME
        value: "1"
      - key: KRAKEN_DRY_RUN
        scope: RUN_TIME
        value: "false"
      - key: BINANCE_DRY_RUN
        scope: RUN_TIME
        value: "false"
      - key: ALPACA_DRY_RUN
        scope: RUN_TIME
        value: "false"

      # Supabase for realtime dashboard data + audit logging
      - key: SUPABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_ANON_KEY
        scope: RUN_TIME
        type: SECRET

      # Frontend build-time vars (if frontend is built in this app image)
      - key: VITE_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      # Exchange/API credentials
      - key: KRAKEN_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: BINANCE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: BINANCE_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: ALPACA_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALPACA_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CAPITAL_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CAPITAL_IDENTIFIER
        scope: RUN_TIME
        type: SECRET
      - key: CAPITAL_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: CAPITAL_DEMO
        scope: RUN_TIME
        value: "false"

      # Optional Redis thought bus (managed DB wiring)
      - key: AUREON_REDIS_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}

# Managed Redis database
# If you already have an external Redis, remove this block and set AUREON_REDIS_URL directly.
databases:
  - name: db
    engine: REDIS
    production: true
    version: "7"
