# ­ЪЉЉ­Ъїї AUREON TRADING SYSTEM - DIGITAL OCEAN APP PLATFORM
# РЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљ
#
# SINGLE SERVICE with PARALLEL PROCESSES via supervisord:
#   1. ­ЪЉЉ Command Center UI (port 8080) - Dashboard & WebSocket
#   2. ­Ъдѕ Orca Kill Cycle - Trading Engine  
#   3. ­ЪДа Autonomous Engine - 9 Intelligence Loops
#   4. ­ЪљЮ Queen Power Redistribution - Energy optimization
#   5. ­ЪЊі Queen Power Dashboard - Real-time monitoring
#   6. ­Ъћё Kraken Cache Feeder - Centralized API access
#
# All processes start together on boot via supervisord.conf
#
# Gary Leckey | January 2026 | DIGITAL OCEAN DEPLOYMENT
# РЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљ

name: aureon-trading
region: lon

services:
  # ­ЪЉЉ MAIN SERVICE - Runs ALL parallel processes via supervisord
  - name: aureon-command-center
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
      repo: RA-CONSULTING/aureon-trading
    
    # HTTP settings for health checks
    http_port: 8080
    instance_count: 1
    instance_size_slug: professional-xs  # 1GB RAM, 0.5 vCPU
    
    # Health check - Command Center /health endpoint
    health_check:
      http_path: /health
      initial_delay_seconds: 120
      period_seconds: 60
      timeout_seconds: 30
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables
    envs:
      # Python settings
      - key: PYTHONUNBUFFERED
        scope: RUN_AND_BUILD_TIME
        value: "1"
      - key: PYTHONIOENCODING
        scope: RUN_AND_BUILD_TIME
        value: "utf-8"
      
      # Aureon settings
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: AUREON_STATE_DIR
        scope: RUN_TIME
        value: /app/state
      - key: AUREON_ENABLE_AUTONOMOUS_CONTROL
        scope: RUN_TIME
        value: "1"
      
      # ­ЪћЦ LIVE TRADING MODE
      - key: LIVE
        scope: RUN_TIME
        value: "1"
      - key: KRAKEN_DRY_RUN
        scope: RUN_TIME
        value: "false"
      - key: BINANCE_DRY_RUN
        scope: RUN_TIME
        value: "false"
      - key: ALPACA_DRY_RUN
        scope: RUN_TIME
        value: "false"
      
      # РЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљ
      # Рџа№ИЈ API KEYS - SET THESE IN DIGITAL OCEAN DASHBOARD Рџа№ИЈ
      # Go to: App > Settings > App-Level Environment Variables
      # РЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљРЋљ
      
      # ­ЪљЎ KRAKEN
      - key: KRAKEN_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_API_SECRET
        scope: RUN_TIME
        type: SECRET
      
      # ­ЪЪА BINANCE
      - key: BINANCE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: BINANCE_API_SECRET
        scope: RUN_TIME
        type: SECRET
      
      # ­ЪдЎ ALPACA
      - key: ALPACA_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALPACA_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      
      # ­Ъњ╝ CAPITAL.COM (CFD Trading)
      - key: CAPITAL_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CAPITAL_IDENTIFIER
        scope: RUN_TIME
        type: SECRET
      - key: CAPITAL_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: CAPITAL_DEMO
        scope: RUN_TIME
        value: "false"
      
      # ­ЪДа Redis for ThoughtBus (optional - uses internal if available)
      - key: AUREON_REDIS_URL
        scope: RUN_TIME
        value: "\${db.REDIS_URL}"

# ­ЪДа Redis Database for ThoughtBus Pub/Sub
databases:
  - name: db
    engine: REDIS
    production: true
    version: "7"
