#!/usr/bin/env python3
"""
aureon_market_energy_field.py — Map the global financial market as ONE energy field.

Every instrument has a frequency. Every bot has a pattern. Every whale
has a signature. The market IS the coupled oscillatory system.

The same Λ(t) that slowed battery drain by 17% maps market energy flows.
Power drains = selling pressure / extraction. Power inputs = buying / accumulation.
The Queen sees the field and trades the flows.

From the HNC Whitepaper:
  "Aureon treats the market not as a random walk but as an acoustic
   chamber filled with standing waves generated by institutional participants."

  9 Archetypal Extraction Patterns:
  1. Solar Clock Algorithm (24h)
  2. Funding Rate Farmer (8h)
  3. Weekend Whale (167.9h)
  4. Cyclic Vector (83.97h)
  + 5 more complex patterns
"""

from __future__ import annotations

import json
import logging
import math
import os
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

_REPO_ROOT = Path(__file__).resolve().parents[2]
log = logging.getLogger("aureon.market_energy")

PHI = 1.618033988749895
SCHUMANN = 7.83


# ═══════════════════════════════════════════════════════════════
#  INSTRUMENT FREQUENCY SIGNATURE
# ═══════════════════════════════════════════════════════════════

@dataclass
class InstrumentSignature:
    """The harmonic fingerprint of one market instrument."""
    symbol: str
    dominant_frequency_hz: float = 0.0      # Primary cycle frequency
    secondary_frequencies: List[float] = field(default_factory=list)
    phase_offset: float = 0.0               # Current phase in cycle
    amplitude: float = 0.0                  # Volatility = amplitude
    energy_state: str = "neutral"           # "accumulating" / "distributing" / "neutral"
    energy_flow_mw: float = 0.0             # Positive = inflow, negative = outflow
    bot_activity: float = 0.0               # 0-1 mechanical pattern strength
    whale_presence: float = 0.0             # 0-1 large player activity
    phi_alignment: float = 0.0             # How close to PHI-ratio cycles
    schumann_coupling: float = 0.0          # How aligned with Earth frequency
    extraction_pattern: str = ""            # Which of the 9 patterns active


@dataclass
class MarketEnergyState:
    """The entire market as one energy field."""
    timestamp: float = 0.0
    total_energy: float = 0.0               # Sum of all instrument energies
    net_flow: float = 0.0                   # Net energy direction
    coherence: float = 0.0                  # How synchronized are instruments
    dominant_frequency: float = 0.0          # Market-wide dominant cycle
    fear_greed: int = 50
    instruments: Dict[str, InstrumentSignature] = field(default_factory=dict)
    extraction_active: bool = False          # Are bots extracting?
    accumulation_active: bool = False        # Are whales accumulating?


# ═══════════════════════════════════════════════════════════════
#  MARKET ENERGY FIELD MAPPER
# ═══════════════════════════════════════════════════════════════

class MarketEnergyField:
    """
    Maps the global financial market as an energy field.
    Each instrument = a frequency. Bots = parasites. Whales = power stations.
    The Queen sees it all as one harmonic system.
    """

    def __init__(self):
        self._state = MarketEnergyState()
        self._price_history: Dict[str, List[float]] = {}
        self._volume_history: Dict[str, List[float]] = {}
        self._time_history: Dict[str, List[float]] = {}
        self._signatures: Dict[str, InstrumentSignature] = {}

        # The 9 extraction patterns and their frequencies
        self._extraction_patterns = {
            "Solar Clock": 1.0 / 24.0,           # 24h cycle in Hz (cycles per hour)
            "Funding Rate Farmer": 1.0 / 8.0,     # 8h cycle
            "Weekend Whale": 1.0 / 167.9,         # ~1 week cycle
            "Cyclic Vector": 1.0 / 83.97,         # ~3.5 day cycle
            "Lunar Cycle": 1.0 / (29.53 * 24),    # Monthly
            "Quarter Pulse": 1.0 / (90 * 24),     # Quarterly
            "FOMC Cycle": 1.0 / (42 * 24),        # ~6 week Fed cycle
            "Options Expiry": 1.0 / (30 * 24),    # Monthly options
            "Asian Session": 1.0 / 24.0,           # Daily but phase-shifted
        }

    def ingest_price(self, symbol: str, price: float, volume: float = 0, timestamp: float = None):
        """Feed one price tick into the field."""
        ts = timestamp or time.time()

        if symbol not in self._price_history:
            self._price_history[symbol] = []
            self._volume_history[symbol] = []
            self._time_history[symbol] = []

        self._price_history[symbol].append(price)
        self._volume_history[symbol].append(volume)
        self._time_history[symbol].append(ts)

        # Keep last 1000 ticks per instrument
        for hist in (self._price_history[symbol], self._volume_history[symbol], self._time_history[symbol]):
            if len(hist) > 1000:
                del hist[:500]

    def compute_signature(self, symbol: str) -> Optional[InstrumentSignature]:
        """Compute the harmonic signature of one instrument from its price history."""
        prices = self._price_history.get(symbol, [])
        volumes = self._volume_history.get(symbol, [])

        if len(prices) < 20:
            return None

        prices_arr = np.array(prices[-200:], dtype=np.float64)
        n = len(prices_arr)

        # Compute returns
        returns = np.diff(prices_arr) / prices_arr[:-1]
        if len(returns) < 10:
            return None

        # FFT on returns — find dominant frequency
        fft = np.fft.rfft(returns)
        magnitudes = np.abs(fft)
        freqs = np.fft.rfftfreq(len(returns))

        # Skip DC component
        if len(magnitudes) > 1:
            peak_idx = np.argmax(magnitudes[1:]) + 1
            dominant_freq = freqs[peak_idx]
            amplitude = magnitudes[peak_idx]
        else:
            dominant_freq = 0
            amplitude = 0

        # Secondary frequencies (top 3)
        if len(magnitudes) > 3:
            top_indices = np.argsort(magnitudes[1:])[-3:] + 1
            secondary = [float(freqs[i]) for i in top_indices if i != peak_idx]
        else:
            secondary = []

        # Energy state: are prices going up (accumulating) or down (distributing)?
        recent_return = (prices_arr[-1] - prices_arr[-10]) / prices_arr[-10] if prices_arr[-10] != 0 else 0
        if recent_return > 0.005:
            energy_state = "accumulating"
        elif recent_return < -0.005:
            energy_state = "distributing"
        else:
            energy_state = "neutral"

        # Energy flow: volume × direction
        if volumes and len(volumes) >= 10:
            recent_vol = np.mean(volumes[-10:])
            energy_flow = recent_vol * recent_return * 1000  # Scale to meaningful number
        else:
            energy_flow = recent_return * 1000

        # Bot activity: check for mechanical periodicity
        # High spectral purity at specific frequencies = bot
        if len(magnitudes) > 5:
            spectral_flatness = np.exp(np.mean(np.log(magnitudes[1:] + 1e-10))) / np.mean(magnitudes[1:] + 1e-10)
            bot_activity = 1.0 - min(1.0, spectral_flatness)  # Low flatness = peaked = bot
        else:
            bot_activity = 0

        # Whale presence: large volume spikes
        if volumes and len(volumes) >= 20:
            vol_arr = np.array(volumes[-20:])
            vol_mean = np.mean(vol_arr)
            vol_max = np.max(vol_arr)
            whale_presence = min(1.0, (vol_max / (vol_mean + 1e-10) - 1) / 5)
        else:
            whale_presence = 0

        # PHI alignment: is the dominant frequency near a PHI ratio of any base?
        phi_alignment = 0
        for base_f in [1/24, 1/8, SCHUMANN/1000]:
            ratio = dominant_freq / base_f if base_f > 0 and dominant_freq > 0 else 0
            if ratio > 0:
                phi_dist = abs(ratio - PHI) / PHI
                if phi_dist < 0.1:
                    phi_alignment = 1.0 - phi_dist * 10

        # Schumann coupling
        schumann_coupling = 0
        if dominant_freq > 0:
            schumann_scaled = SCHUMANN / 1000  # Scale Schumann to market timeframe
            ratio = dominant_freq / schumann_scaled if schumann_scaled > 0 else 0
            # Check if ratio is near an integer or PHI
            if ratio > 0:
                nearest_int = round(ratio)
                int_dist = abs(ratio - nearest_int)
                phi_dist = abs(ratio - PHI)
                schumann_coupling = max(0, 1.0 - min(int_dist, phi_dist) * 5)

        # Extraction pattern matching
        extraction_pattern = ""
        for pattern_name, pattern_freq in self._extraction_patterns.items():
            if dominant_freq > 0 and pattern_freq > 0:
                ratio = dominant_freq / pattern_freq
                if 0.9 < ratio < 1.1:  # Within 10% of pattern frequency
                    extraction_pattern = pattern_name
                    break

        sig = InstrumentSignature(
            symbol=symbol,
            dominant_frequency_hz=float(dominant_freq),
            secondary_frequencies=secondary,
            phase_offset=float(np.angle(fft[peak_idx])) if len(fft) > peak_idx else 0,
            amplitude=float(amplitude),
            energy_state=energy_state,
            energy_flow_mw=float(energy_flow),
            bot_activity=float(bot_activity),
            whale_presence=float(whale_presence),
            phi_alignment=float(phi_alignment),
            schumann_coupling=float(schumann_coupling),
            extraction_pattern=extraction_pattern,
        )

        self._signatures[symbol] = sig
        return sig

    def compute_field(self) -> MarketEnergyState:
        """Compute the entire market energy field from all instrument signatures."""
        sigs = list(self._signatures.values())
        if not sigs:
            return self._state

        # Total energy = sum of amplitudes
        total_energy = sum(s.amplitude for s in sigs)

        # Net flow = sum of directional flows
        net_flow = sum(s.energy_flow_mw for s in sigs)

        # Coherence = how synchronized are the instruments
        if len(sigs) >= 2:
            phases = [s.phase_offset for s in sigs if s.phase_offset != 0]
            if phases:
                # Circular variance of phases
                mean_sin = np.mean(np.sin(phases))
                mean_cos = np.mean(np.cos(phases))
                coherence = float(np.sqrt(mean_sin**2 + mean_cos**2))
            else:
                coherence = 0
        else:
            coherence = 0

        # Market-wide dominant frequency
        all_freqs = [s.dominant_frequency_hz for s in sigs if s.dominant_frequency_hz > 0]
        dominant_freq = float(np.median(all_freqs)) if all_freqs else 0

        # Extraction detection
        extraction_active = any(s.bot_activity > 0.5 and s.extraction_pattern for s in sigs)
        accumulation_active = any(s.whale_presence > 0.5 and s.energy_state == "accumulating" for s in sigs)

        self._state = MarketEnergyState(
            timestamp=time.time(),
            total_energy=total_energy,
            net_flow=net_flow,
            coherence=coherence,
            dominant_frequency=dominant_freq,
            instruments={s.symbol: s for s in sigs},
            extraction_active=extraction_active,
            accumulation_active=accumulation_active,
        )

        return self._state

    def get_trading_signals(self) -> List[Dict[str, Any]]:
        """Generate trading signals from the energy field."""
        signals = []

        for sym, sig in self._signatures.items():
            signal = {
                "symbol": sym,
                "action": "HOLD",
                "confidence": 0.0,
                "reason": "",
            }

            # Accumulation + low bot activity = BUY signal
            if sig.energy_state == "accumulating" and sig.bot_activity < 0.3 and sig.whale_presence > 0.3:
                signal["action"] = "BUY"
                signal["confidence"] = min(1.0, sig.whale_presence + sig.phi_alignment)
                signal["reason"] = f"Whale accumulation, low bot activity, energy flowing IN"

            # Distribution + high bot activity = extraction happening = AVOID
            elif sig.energy_state == "distributing" and sig.bot_activity > 0.5:
                signal["action"] = "SELL"
                signal["confidence"] = min(1.0, sig.bot_activity)
                signal["reason"] = f"Extraction pattern: {sig.extraction_pattern or 'mechanical'}"

            # PHI-aligned + accumulating = golden opportunity
            elif sig.phi_alignment > 0.5 and sig.energy_state == "accumulating":
                signal["action"] = "BUY"
                signal["confidence"] = sig.phi_alignment
                signal["reason"] = f"PHI-aligned cycle, natural accumulation"

            # Schumann-coupled instruments tend to mean-revert
            elif sig.schumann_coupling > 0.5 and sig.energy_state == "distributing":
                signal["action"] = "BUY"
                signal["confidence"] = sig.schumann_coupling * 0.7
                signal["reason"] = f"Schumann-coupled, expecting mean reversion"

            if signal["action"] != "HOLD":
                signals.append(signal)

        return sorted(signals, key=lambda x: -x["confidence"])

    def display(self) -> str:
        """Human-readable energy field display."""
        s = self._state
        lines = [
            f"MARKET ENERGY FIELD",
            f"  Total energy:  {s.total_energy:.4f}",
            f"  Net flow:      {s.net_flow:+.4f} ({'inflow' if s.net_flow > 0 else 'outflow'})",
            f"  Coherence:     {s.coherence:.3f}",
            f"  Dominant freq: {s.dominant_frequency:.6f}",
            f"  Extraction:    {'ACTIVE' if s.extraction_active else 'quiet'}",
            f"  Accumulation:  {'ACTIVE' if s.accumulation_active else 'quiet'}",
            f"",
        ]

        for sym, sig in sorted(s.instruments.items()):
            state_icon = "+" if sig.energy_state == "accumulating" else "-" if sig.energy_state == "distributing" else "="
            bot_bar = "#" * int(sig.bot_activity * 5)
            whale_bar = "@" * int(sig.whale_presence * 5)
            lines.append(
                f"  {state_icon} {sym:10s} freq={sig.dominant_frequency_hz:.4f} "
                f"amp={sig.amplitude:.2f} bot=[{bot_bar:5s}] whale=[{whale_bar:5s}] "
                f"phi={sig.phi_alignment:.2f} {sig.extraction_pattern}"
            )

        return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════
#  STANDALONE TEST
# ═══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import sys, io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

    # Load .env
    for line in (_REPO_ROOT / ".env").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            os.environ.setdefault(k.strip(), v.strip())

    print("MARKET ENERGY FIELD — Live mapping")
    print("=" * 60)

    field = MarketEnergyField()

    # Pull live prices
    try:
        import requests
        r = requests.get("https://api.coingecko.com/api/v3/coins/markets",
                         params={"vs_currency": "usd", "order": "market_cap_desc",
                                 "per_page": 20, "page": 1, "sparkline": True},
                         timeout=10)
        if r.status_code == 200:
            coins = r.json()
            for coin in coins:
                sym = coin.get("symbol", "?").upper()
                sparkline = coin.get("sparkline_in_7d", {}).get("price", [])
                volume = coin.get("total_volume", 0)

                # Feed sparkline as price history
                for i, price in enumerate(sparkline):
                    field.ingest_price(sym, price, volume / len(sparkline), time.time() - (len(sparkline) - i) * 3600)

                sig = field.compute_signature(sym)
                if sig:
                    print(f"  {sym:6s} freq={sig.dominant_frequency_hz:.4f} "
                          f"state={sig.energy_state:13s} bot={sig.bot_activity:.2f} "
                          f"whale={sig.whale_presence:.2f} phi={sig.phi_alignment:.2f}")

            # Compute full field
            state = field.compute_field()
            print(f"\n{field.display()}")

            # Trading signals
            signals = field.get_trading_signals()
            if signals:
                print(f"\nTRADING SIGNALS:")
                for s in signals[:5]:
                    print(f"  {s['action']:4s} {s['symbol']:6s} conf={s['confidence']:.2f} — {s['reason']}")

    except Exception as e:
        print(f"  Error: {e}")
