name: aureon-command-center
region: lon1
services:
  - name: aureon
    github:
      repo: Gary-leckey/aureon-trading
      branch: main
      deploy_on_push: true
    source_dir: /
    environment_slug: python
    build_command: pip install -r requirements.txt
    run_command: supervisord -n -c deploy/supervisord.conf
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "8080"
      - key: AUREON_STATE_DIR
        value: /tmp/aureon_state
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONIOENCODING
        value: "utf-8"
