// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use env vars with fallbacks for preview environments
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? 'https://owfeyxrfyhprpcgqwxqh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93ZmV5eHJmeWhwcnBjZ3F3eHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyOTU5MTksImV4cCI6MjA3ODg3MTkxOX0.sb5uA0adyyVazBItAL3pk9Gm7qCZJoYnwc3W7LvPFAQ';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});