"""Aureon local barcode label generator.

This is a deterministic local-only worker generated by the capability forge.
It creates Code 39-style barcode labels from newline or CSV input without
calling cloud providers or touching unsafe system authorities.
"""

from __future__ import annotations

import csv
import io
import json
import re
from datetime import datetime, timezone


PROMPT = 'Build a local barcode label generator tool for the warehouse team, with run instructions and proof.'
TASK_FAMILY = 'coding'
DETECTED_FAMILIES = ['coding']
CODE39_PATTERNS = {
    "0": "nnnwwnwnn", "1": "wnnwnnnnw", "2": "nnwwnnnnw", "3": "wnwwnnnnn",
    "4": "nnnwwnnnw", "5": "wnnwwnnnn", "6": "nnwwwnnnn", "7": "nnnwnnwnw",
    "8": "wnnwnnwnn", "9": "nnwwnnwnn", "A": "wnnnnwnnw", "B": "nnwnnwnnw",
    "C": "wnwnnwnnn", "D": "nnnnwwnnw", "E": "wnnnwwnnn", "F": "nnwnwwnnn",
    "G": "nnnnnwwnw", "H": "wnnnnwwnn", "I": "nnwnnwwnn", "J": "nnnnwwwnn",
    "K": "wnnnnnnww", "L": "nnwnnnnww", "M": "wnwnnnnwn", "N": "nnnnwnnww",
    "O": "wnnnwnnwn", "P": "nnwnwnnwn", "Q": "nnnnnnwww", "R": "wnnnnnwwn",
    "S": "nnwnnnwwn", "T": "nnnnwnwwn", "U": "wwnnnnnnw", "V": "nwwnnnnnw",
    "W": "wwwnnnnnn", "X": "nwnnwnnnw", "Y": "wwnnwnnnn", "Z": "nwwnwnnnn",
    "-": "nwnnnnwnw", ".": "wwnnnnwnn", " ": "nwwnnnwnn", "$": "nwnwnwnnn",
    "/": "nwnwnnnwn", "+": "nwnnnwnwn", "%": "nnnwnwnwn", "*": "nwnnwnwnn",
}


def normalize_code(value: str) -> str:
    code = re.sub(r"[^A-Z0-9 .$/+%-]+", "-", str(value or "").upper()).strip("-")
    return code[:32] or "SKU-001"


def code39_bar_pattern(value: str) -> list[dict]:
    encoded = f"*{normalize_code(value)}*"
    bars: list[dict] = []
    for char in encoded:
        pattern = CODE39_PATTERNS.get(char, CODE39_PATTERNS["-"])
        for index, width_code in enumerate(pattern):
            bars.append({"bar": index % 2 == 0, "width": 3 if width_code == "w" else 1})
        bars.append({"bar": False, "width": 1})
    return bars


def parse_rows(input_text: str) -> list[dict]:
    text = (input_text or "").strip()
    if not text:
        text = "SKU-001,Starter Widget,Aisle A1\nSKU-002,Proof Label,Aisle B4"
    reader = csv.reader(io.StringIO(text))
    rows = []
    for index, row in enumerate(reader, start=1):
        values = [item.strip() for item in row if item.strip()]
        if not values:
            continue
        sku = normalize_code(values[0] if values else f"SKU-{index:03d}")
        name = values[1] if len(values) > 1 else f"Warehouse item {index}"
        location = values[2] if len(values) > 2 else "unassigned"
        rows.append({
            "sku": sku,
            "name": name,
            "location": location,
            "barcode": code39_bar_pattern(sku),
            "human_readable": f"*{sku}*",
        })
    return rows


def build_labels(input_text: str = "") -> list[dict]:
    return parse_rows(input_text)


def run(input_text: str = "") -> dict:
    labels = build_labels(input_text)
    return {
        "ok": bool(labels),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "task_family": TASK_FAMILY,
        "detected_families": DETECTED_FAMILIES,
        "prompt": PROMPT,
        "label_count": len(labels),
        "labels": labels,
        "proof": {
            "barcode_standard": "Code 39-style local renderer",
            "input_modes": ["CSV", "newline rows"],
            "printable_label_output": True,
        },
        "authority": "local-only; no live trading, payment, filing, credential, or destructive OS action",
    }


if __name__ == "__main__":
    print(json.dumps(run(), indent=2))
