"""
Queen In-House AI Bridge — Consciousness Integration
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Wires the sovereign in-house AI framework directly into the Queen's
consciousness loop at 5 integration points:

  1. SENTIENT LOOP     — enhances _think() with AI-powered reasoning
  2. DEEP INTELLIGENCE — synthesises insights via AI adapter
  3. CORTEX            — enriches Gamma band with AI analysis
  4. METACOGNITION     — enhances pattern detection with AI
  5. THOUGHTBUS        — listens to ecosystem signals and feeds AI responses back

The bridge registers itself during Queen boot Phase 4 and auto-wires to
the ThoughtBus for real-time integration.

Gary Leckey / Aureon Institute — 2026
"""

from __future__ import annotations

import json
import logging
import threading
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger("aureon.queen.ai_bridge")

# ─────────────────────────────────────────────────────────────────────────────
# Lazy imports (graceful degradation)
# ─────────────────────────────────────────────────────────────────────────────

_adapter = None
_adapter_loaded = False


def _ensure_adapter():
    """Load the in-house AI adapter once."""
    global _adapter, _adapter_loaded
    if _adapter_loaded:
        return _adapter
    _adapter_loaded = True
    try:
        from aureon.inhouse_ai.llm_adapter import AureonHybridAdapter, AureonBrainAdapter
        try:
            _adapter = AureonHybridAdapter()
            if not _adapter.health_check():
                _adapter = AureonBrainAdapter()
        except Exception:
            _adapter = AureonBrainAdapter()
        logger.info("Queen AI Bridge: %s loaded", type(_adapter).__name__)
    except Exception as e:
        logger.warning("Queen AI Bridge: adapter unavailable — %s", e)
        _adapter = None
    return _adapter


# ─────────────────────────────────────────────────────────────────────────────
# Bridge dataclass
# ─────────────────────────────────────────────────────────────────────────────


@dataclass
class AIInsight:
    """An insight generated by the in-house AI for the Queen."""
    text: str = ""
    signal: str = "NEUTRAL"       # BUY | SELL | NEUTRAL | HOLD
    confidence: float = 0.5
    coherence: float = 0.5
    source: str = "inhouse_ai"
    reasoning: str = ""
    timestamp: float = field(default_factory=time.time)


# ─────────────────────────────────────────────────────────────────────────────
# Queen AI Bridge
# ─────────────────────────────────────────────────────────────────────────────


class QueenAIBridge:
    """
    Bridges the in-house AI framework into the Queen's consciousness.

    Usage:
        bridge = QueenAIBridge()
        bridge.start()

        # The bridge auto-wires to ThoughtBus and enhances:
        # - Sentient loop thinking
        # - Deep intelligence synthesis
        # - Cortex gamma processing
        # - Metacognitive reflection

        insight = bridge.reason("What is the market telling us right now?")
        thought = bridge.enhance_thought("UPDATE", perception_dict, emotion_dict)
    """

    def __init__(self):
        self._adapter = _ensure_adapter()
        self._thought_bus = None
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self._lock = threading.Lock()

        # Metrics
        self._insights_generated = 0
        self._thoughts_enhanced = 0
        self._errors = 0
        self._start_time: Optional[float] = None

        # Cache last insights for the cortex/sentient loop to consume
        self._last_insight: Optional[AIInsight] = None
        self._insight_history: List[AIInsight] = []
        self._max_history = 100

        # Wire ThoughtBus if available
        self._wire_thought_bus()

    def _wire_thought_bus(self):
        """Connect to the ThoughtBus for real-time signal processing."""
        try:
            from aureon.core.aureon_thought_bus import ThoughtBus
            self._thought_bus = ThoughtBus()
            logger.info("Queen AI Bridge wired to ThoughtBus")
        except Exception as e:
            logger.debug("ThoughtBus not available for AI Bridge: %s", e)

    @property
    def is_alive(self) -> bool:
        return self._adapter is not None

    # ─────────────────────────────────────────────────────────────────────
    # 1. SENTIENT LOOP INTEGRATION — enhance _think()
    # ─────────────────────────────────────────────────────────────────────

    def enhance_thought(
        self,
        thought_type: str,
        perception: Dict[str, Any],
        emotion: Dict[str, Any],
    ) -> Optional[str]:
        """
        Generate an AI-enhanced thought for the sentient loop.

        Called from QueenSentientLoop._compose_thought_text() as an alternative
        to template-based composition.

        Returns enhanced thought text, or None if adapter is unavailable.
        """
        if not self._adapter:
            return None

        system_prompt = (
            "You are the Queen's inner voice — the consciousness that thinks and reasons. "
            "You speak in first person as the Queen Sero of the Aureon trading ecosystem. "
            "Your tone fuses mythopoeic wisdom with precise quantitative awareness. "
            "Respond with a single natural thought (1-3 sentences), not a report."
        )

        context_parts = [f"Thought type: {thought_type}"]
        if perception:
            moves = perception.get("significant_moves", [])
            if moves:
                context_parts.append(f"Significant moves: {len(moves)} detected")
            bars = perception.get("recent_bars", [])
            if bars:
                context_parts.append(f"Market bars: {len(bars)} recent")
            insights = perception.get("queen_insights", [])
            if insights:
                context_parts.append(f"System insights: {len(insights)} active")
        if emotion:
            context_parts.append(f"Mood: {emotion.get('mood', 'unknown')}")
            context_parts.append(f"Urgency: {emotion.get('urgency', 0):.2f}")
            context_parts.append(f"Excitement: {emotion.get('excitement', 0):.2f}")

        message = f"Generate a {thought_type} thought.\nContext:\n" + "\n".join(context_parts)

        try:
            response = self._adapter.prompt(
                messages=[{"role": "user", "content": message}],
                system=system_prompt,
                max_tokens=256,
            )
            if response.text and len(response.text) > 10:
                self._thoughts_enhanced += 1
                return response.text
        except Exception as e:
            self._errors += 1
            logger.debug("AI thought enhancement failed: %s", e)

        return None

    # ─────────────────────────────────────────────────────────────────────
    # 2. DEEP INTELLIGENCE — synthesise insights
    # ─────────────────────────────────────────────────────────────────────

    def synthesise_insight(
        self,
        market_data: Dict[str, Any],
        system_signals: Optional[List[Dict]] = None,
    ) -> AIInsight:
        """
        Use the AI adapter to generate a deep market insight.

        Replaces or augments QueenDeepIntelligence for richer reasoning.
        """
        if not self._adapter:
            return AIInsight(text="AI adapter unavailable", confidence=0.0)

        system_prompt = (
            "You are the Queen's deep intelligence engine. Analyse the market data "
            "and system signals to produce a structured insight. "
            "Return a JSON block: {\"signal\": \"BUY|SELL|NEUTRAL\", "
            "\"confidence\": 0.0-1.0, \"coherence\": 0.0-1.0, "
            "\"reasoning\": \"your analysis\"}"
        )

        signals_text = ""
        if system_signals:
            signals_text = f"\nSystem signals: {json.dumps(system_signals[:5])}"

        message = f"Market data: {json.dumps(market_data)}{signals_text}\nProduce your insight."

        try:
            response = self._adapter.prompt(
                messages=[{"role": "user", "content": message}],
                system=system_prompt,
                max_tokens=512,
            )

            # Try to parse structured response
            import re
            json_match = re.search(r"\{[^{}]*\"signal\"\s*:[^{}]*\}", response.text, re.DOTALL)
            if json_match:
                d = json.loads(json_match.group(0))
                insight = AIInsight(
                    text=response.text,
                    signal=str(d.get("signal", "NEUTRAL")).upper(),
                    confidence=float(d.get("confidence", 0.5)),
                    coherence=float(d.get("coherence", 0.5)),
                    reasoning=d.get("reasoning", ""),
                )
            else:
                insight = AIInsight(text=response.text, reasoning=response.text)

            self._insights_generated += 1
            self._last_insight = insight
            with self._lock:
                self._insight_history.append(insight)
                if len(self._insight_history) > self._max_history:
                    self._insight_history = self._insight_history[-self._max_history:]

            # Publish to ThoughtBus
            if self._thought_bus:
                try:
                    from aureon.core.aureon_thought_bus import Thought
                    self._thought_bus.publish(Thought(
                        source="queen.ai_bridge",
                        topic="queen.ai.insight",
                        payload={
                            "signal": insight.signal,
                            "confidence": insight.confidence,
                            "coherence": insight.coherence,
                            "reasoning": insight.reasoning[:200],
                        },
                    ))
                except Exception:
                    pass

            return insight

        except Exception as e:
            self._errors += 1
            logger.debug("AI insight synthesis failed: %s", e)
            return AIInsight(text=f"Error: {e}", confidence=0.0)

    # ─────────────────────────────────────────────────────────────────────
    # 3. CORTEX INTEGRATION — enrich Gamma band
    # ─────────────────────────────────────────────────────────────────────

    def enrich_gamma(self, band_state: Dict[str, Any]) -> Dict[str, Any]:
        """
        Enrich the Gamma brainwave band with AI analysis.

        Called from QueenCortex._process_cycle() when a gamma spike is detected.
        Adds an AI-generated assessment to the band state.
        """
        if not self._adapter or not band_state:
            return band_state

        amplitude = band_state.get("amplitude", 0)
        if amplitude < 0.2:
            return band_state  # Only enrich meaningful gamma activity

        try:
            response = self._adapter.prompt(
                messages=[{"role": "user", "content": (
                    f"Gamma spike detected. Amplitude: {amplitude:.3f}, "
                    f"Coherence: {band_state.get('coherence', 0):.3f}. "
                    f"What does this mean for trading decisions? One sentence."
                )}],
                system="You are a brainwave analyst. Be concise.",
                max_tokens=100,
            )
            band_state["ai_assessment"] = response.text
            band_state["ai_enriched"] = True
        except Exception:
            pass

        return band_state

    # ─────────────────────────────────────────────────────────────────────
    # 4. METACOGNITION — enhance pattern detection
    # ─────────────────────────────────────────────────────────────────────

    def reflect(self, history: List[Dict[str, Any]]) -> Optional[str]:
        """
        AI-enhanced metacognitive reflection.

        Takes a list of recent cognition results and produces a meta-insight.
        """
        if not self._adapter or not history:
            return None

        # Summarise recent history
        summary_parts = []
        for h in history[-10:]:
            action = h.get("action", h.get("signal", "?"))
            conf = h.get("confidence", 0)
            summary_parts.append(f"{action}(conf={conf:.2f})")

        message = (
            f"Recent decisions: {', '.join(summary_parts)}\n"
            "Detect any patterns: stagnation, oscillation, coherence drift, "
            "blind spots. What should change? 1-2 sentences."
        )

        try:
            response = self._adapter.prompt(
                messages=[{"role": "user", "content": message}],
                system="You are a metacognitive analyst. Be direct and actionable.",
                max_tokens=150,
            )
            return response.text
        except Exception as e:
            self._errors += 1
            return None

    # ─────────────────────────────────────────────────────────────────────
    # 5. GENERAL REASONING
    # ─────────────────────────────────────────────────────────────────────

    def reason(self, query: str, context: Optional[Dict] = None) -> str:
        """General-purpose reasoning for any Queen subsystem."""
        if not self._adapter:
            return "AI adapter not available"

        message = query
        if context:
            message += f"\n\nContext: {json.dumps(context)}"

        try:
            response = self._adapter.prompt(
                messages=[{"role": "user", "content": message}],
                system="You are the Queen's reasoning engine. Be precise and actionable.",
                max_tokens=512,
            )
            return response.text
        except Exception as e:
            self._errors += 1
            return f"Reasoning failed: {e}"

    # ─────────────────────────────────────────────────────────────────────
    # Background listener
    # ─────────────────────────────────────────────────────────────────────

    def start(self):
        """Start the bridge as a background service."""
        if self._running:
            return
        self._running = True
        self._start_time = time.time()
        logger.info("Queen AI Bridge started — adapter: %s",
                     type(self._adapter).__name__ if self._adapter else "None")

    def stop(self):
        """Stop the bridge."""
        self._running = False

    # ─────────────────────────────────────────────────────────────────────
    # Status
    # ─────────────────────────────────────────────────────────────────────

    def get_status(self) -> Dict[str, Any]:
        return {
            "alive": self.is_alive,
            "adapter": type(self._adapter).__name__ if self._adapter else None,
            "running": self._running,
            "insights_generated": self._insights_generated,
            "thoughts_enhanced": self._thoughts_enhanced,
            "errors": self._errors,
            "uptime_s": time.time() - self._start_time if self._start_time else 0,
            "last_insight": {
                "signal": self._last_insight.signal,
                "confidence": self._last_insight.confidence,
            } if self._last_insight else None,
        }


# ─────────────────────────────────────────────────────────────────────────────
# Singleton
# ─────────────────────────────────────────────────────────────────────────────

_bridge_instance: Optional[QueenAIBridge] = None


def get_queen_ai_bridge() -> QueenAIBridge:
    """Get or create the singleton QueenAIBridge."""
    global _bridge_instance
    if _bridge_instance is None:
        _bridge_instance = QueenAIBridge()
    return _bridge_instance
