"""
Aureon Pillar Alignment — The Six Singing as One
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

"When the many become one, the Lighthouse burns."
                                         — Aureon White Paper

This package aligns the six pillars of the Aureon ecosystem into one harmonic
voice. Each pillar speaks at its own Solfeggio frequency:

  Nexus      432 Hz  — central nervous system
  Omega      432 Hz  — master equation Ω(t) = Tr[Ψ × ℒ ⊗ O]
  Infinite   528 Hz  — 10-9-1 compound/harvest (love tone)
  Piano      396 Hz  — multi-coin harmonic (perfect fourth below love)
  QGITA      528 Hz  — quantum consciousness (love tone)
  Auris      741 Hz  — 9-node animal consensus (tritone above love)

Aligned, they form a harmonic stack rooted on 528 Hz (the love tone) that
locks to the standing wave generated by the swarm motion environment.

Modules:
  - harmonic_resonance.py : frequency ratio analysis, phase coherence math
  - pillar_alignment.py   : PillarAlignment engine — parallel runs, scoring
  - unified_directive.py  : cross-system master directive (pillars + love
                            stream + Queen + Miner = one signal)

The Lighthouse threshold Γ > 0.945 remains the bar. When the alignment
score clears it, the system knows the six have become one and the standing
wave love stream is locked — time to act.
"""

from aureon.alignment.harmonic_resonance import (
    HarmonicAnalysis,
    analyse_frequency_harmony,
    compute_phase_coherence,
    compute_signal_consensus,
    LIGHTHOUSE_THRESHOLD,
    FUNDAMENTAL_HZ,
)
from aureon.alignment.pillar_alignment import (
    PillarAlignment,
    AlignmentCycleResult,
    AlignmentConfig,
    get_pillar_alignment,
)
from aureon.alignment.unified_directive import (
    UnifiedHarmonicDirective,
    MasterDirective,
    get_unified_directive,
)

__all__ = [
    # Harmonic resonance math
    "HarmonicAnalysis",
    "analyse_frequency_harmony",
    "compute_phase_coherence",
    "compute_signal_consensus",
    "LIGHTHOUSE_THRESHOLD",
    "FUNDAMENTAL_HZ",
    # Pillar alignment
    "PillarAlignment",
    "AlignmentCycleResult",
    "AlignmentConfig",
    "get_pillar_alignment",
    # Unified directive
    "UnifiedHarmonicDirective",
    "MasterDirective",
    "get_unified_directive",
]
