"""
Generated by Aureon's local full-stack agent forge.
This backend uses only Python standard library modules and stores demo data locally.
"""
from __future__ import annotations

import argparse
import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, Dict, List, Tuple


BUILD_ID = "35f63ccbc2de"
DATA_PATH = Path(__file__).with_name("data_store.json")


def create_initial_state() -> Dict[str, Any]:
    return {
        "build_id": BUILD_ID,
        "items": [
            {"id": "task-001", "title": "Scope client brief", "owner": "Product Manager", "status": "ready"},
            {"id": "task-002", "title": "Build API contract", "owner": "API Engineer", "status": "in_progress"},
            {"id": "task-003", "title": "Run integration proof", "owner": "Test Pilot", "status": "queued"},
        ],
    }


def load_state() -> Dict[str, Any]:
    if DATA_PATH.exists():
        try:
            return json.loads(DATA_PATH.read_text(encoding="utf-8"))
        except Exception:
            return create_initial_state()
    state = create_initial_state()
    save_state(state)
    return state


def save_state(state: Dict[str, Any]) -> None:
    DATA_PATH.write_text(json.dumps(state, indent=2, sort_keys=True), encoding="utf-8")


def health_check(state: Dict[str, Any]) -> Dict[str, Any]:
    return {"ok": True, "service": "aureon-full-stack-35f63ccbc2de", "build_id": state.get("build_id", BUILD_ID)}


def list_items(state: Dict[str, Any]) -> List[Dict[str, Any]]:
    return list(state.get("items", []))


def validate_item(payload: Dict[str, Any]) -> Tuple[bool, str]:
    if not str(payload.get("title") or "").strip():
        return False, "title_required"
    if not str(payload.get("owner") or "").strip():
        return False, "owner_required"
    return True, "ok"


def create_item(state: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
    valid, reason = validate_item(payload)
    if not valid:
        raise ValueError(reason)
    item = {
        "id": f"task-{len(state.get('items', [])) + 1:03d}",
        "title": str(payload.get("title")).strip(),
        "owner": str(payload.get("owner")).strip(),
        "status": str(payload.get("status") or "queued"),
    }
    state.setdefault("items", []).append(item)
    return item


def dashboard_summary(state: Dict[str, Any]) -> Dict[str, Any]:
    items = list_items(state)
    return {
        "total": len(items),
        "ready": len([item for item in items if item.get("status") == "ready"]),
        "in_progress": len([item for item in items if item.get("status") == "in_progress"]),
        "queued": len([item for item in items if item.get("status") == "queued"]),
    }


class Handler(BaseHTTPRequestHandler):
    def _send(self, status: int, payload: Any) -> None:
        body = json.dumps(payload, indent=2).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Headers", "content-type")
        self.send_header("Access-Control-Allow-Methods", "GET,POST,OPTIONS")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self) -> None:
        self._send(200, {"ok": True})

    def do_GET(self) -> None:
        state = load_state()
        if self.path == "/api/health":
            self._send(200, health_check(state))
        elif self.path == "/api/items":
            self._send(200, {"items": list_items(state), "summary": dashboard_summary(state)})
        else:
            self._send(404, {"error": "not_found", "path": self.path})

    def do_POST(self) -> None:
        state = load_state()
        if self.path != "/api/items":
            self._send(404, {"error": "not_found", "path": self.path})
            return
        length = int(self.headers.get("Content-Length") or "0")
        payload = json.loads(self.rfile.read(length).decode("utf-8") or "{}")
        try:
            item = create_item(state, payload)
            save_state(state)
            self._send(201, {"item": item, "summary": dashboard_summary(state)})
        except ValueError as exc:
            self._send(400, {"error": str(exc)})


def run(port: int = 8787) -> None:
    server = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    print(f"Aureon full-stack API listening at http://127.0.0.1:{port}")
    server.serve_forever()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=8787)
    args = parser.parse_args()
    run(args.port)
